name: Backend Security Cloud Test

#trigger every push
on: [push]

jobs: 
  run-security-check:
    runs-on: windows-latest #or you can use ubuntu/macos depending how you want it

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Simulate Secure Database Connection
        env:
          DB_PASS: ${{ secrets.TESTING }}
        shell: bash
        run: |
          echo "Cloud active"
          echo "Checking database"
          echo "$TESTING $DB_PASS"

        with:
          script: |
            import os
            print(os.getenv("TESTING"))
            print(os.getenv("DB_PASS"))
            print("End of python")


