name: Backend Security Cloud Test

#trigger every push
on: [push]

jobs: 
  run-security-check:
    runs-on: windows-latest #or you can use ubuntu/macos depending how you want it

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Simulate Secure Database Connection
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
        shell: bash
        run: |
          echo "Cloud active"
          echo "Checking database"
          # trial and error
          echo "$DB_PASS"


